* dezero-naive

DeZero in Common Lisp

* Requirements

- [[http://www.sbcl.org/][Steel Bank Common Lisp]]
- [[https://www.quicklisp.org/beta/][Quicklisp]]
- [[https://lisp-stat.dev/docs/manuals/array-operations/][Array Operations]]
- [[https://trivial-garbage.common-lisp.dev/][Trivial Garbage]]
- [[https://github.com/fukamachi/rove][Rove]]

* Installation

Clone the repo to =~/common-lisp/dezero-naive= dicrectory.

#+begin_src shell
git clone https://github.com/elderica/dezero-naive.git ~/common-lisp/dezero-naive
#+end_src

Then load the system.

#+begin_src lisp
(ql:quickload :dezero-naive)
#+end_src

* Usage

** TODO Fill me in

* Tests

The =dezero-naive= tests are provided as part of the
=:dezero-naive.test= system.

In order to run the tests you can evaluate the following expressions.

#+begin_src lisp
CL-USER> (ql:quickload :dezero-naive.test)
CL-USER> (asdf:test-system :dezero-naive.test)
#+end_src

* GNU Makefile

~Makefile~ has several targets.

- ~test~ runs test suites.
- ~sb-cover~ collects code coverage using ~:sb-cover~.
- ~build-image~ builds docker image.
- ~test-image~ runs test suites in docker container.

* Contributing

=dezero-naive= is hosted on [[https://github.com/elderica/dezero-naive][Github]]. Please contribute by reporting
issues, suggesting features or by sending patches using pull requests.

* Authors

- elderica <[[mailto:1130138+elderica@users.noreply.github.com][1130138+elderica@users.noreply.github.com]]>

* License

This project is Open Source and licensed under the [[http://opensource.org/licenses/BSD-2-Clause][BSD License]].
